#!/bin/sh

dir=$(cd "${0%[/\\]*}" > /dev/null; pwd)

if [[ $(uname -s) == CYGWIN_* ]]; then    
    # cygwin paths for windows PHP must be translated
    dir=$(cygpath -m "$dir");    
fi

php "${dir}/composer.phar" "$@"
