#!/bin/sh

dir=$(cd "${0%[/\\]*}" > /dev/null; pwd)

if [ -d /proc/cygdrive ]; then
    cygwin_root=$(cygpath -m /)
    php_bin=$(cygpath -m "$(which php)")

    case "$php_bin" in
        "$cygwin_root"/*)
            # We are using Cygwin PHP, no action necessary
            ;;
        *)
            # We are using Windows PHP, so the path must be translated
            dir=$(cygpath -m "$dir")
            ;;
    esac
fi

php "${dir}/composer.phar" "$@"
