#!/bin/sh

dir=$(d=$(dirname "$0"); cd "$d" && pwd)

# see if we are running in cygwin
if [[ $dir == /cygdrive/* ]]; then

    # translate to windows format if we are using windows PHP
	if [[ $(which php) == /cygdrive/* ]]; then
  		dir=$(cygpath -m $dir);
  	fi
fi

# escape any spaces
dir=$(echo $dir | sed 's/ /\ /g')
php "${dir}/composer.phar" $*
